# -*- makefile-gmake -*-

prolog
sp(a).
sp(b).
sp(c).
endprolog

ABC = $(bagof X,sp(X))
DEF = $(bagof X,nonexistent_predicate(X))

bagof1:
	echo $(ABC) >$@

bagof2:
	echo $(DEF) >$@

prolog
foo(a,1).
foo(b,2).
foo(c,3).
endprolog

bagof3: bagoff-param-b-bagof3

bagoff-param-$(P)-$(OUT):
	echo $(bagof X,foo($(P),X)) > $(OUT)
